Add support for `useCopyTextHandler` options
mfix22/actionsack pull request #10
Opened 2021-02-03 09:46 UTC by Arriv9l

[copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard) now support copy with options.

2021-02-05 03:29 UTC, mfix22 requested changes
Couple quick things. Thanks for doing this @Arriv9l !

2021-02-05 03:29 UTC, mfix22 commented on src/CopyButton.js
> +export function useCopyTextHandler(textToCopy, { interval, options } = {}) {
@Arriv9l can we just make options a part of the second param? 

Something like
```suggestion
export function useCopyTextHandler(textToCopy, { interval, ...options } = {}) {
```

2021-02-05 03:29 UTC, mfix22 commented on src/CopyButton.js
> +  return props.children(useCopyTextHandler(props.text, { interval: props.interval, options: props.options }))
This will need updating too

2021-02-05 03:29 UTC, mfix22 commented on README.md
> +For more information about `options`, see [API](https://github.com/sudodoki/copy-to-clipboard#api).
Love this 👍

2021-02-05 03:29 UTC, mfix22 commented on README.md
> +    interval, options
just inline `options` above, here

2021-02-06 23:39 UTC, mfix22 requested changes
Really close! Would like to avoid making "breaking" changes

2021-02-06 23:39 UTC, mfix22 commented on src/CopyButton.js
> +  return props.children(useCopyTextHandler(props.text, props.options))
`props.interval` must remain, otherwise this would be a breaking change. 

Can we just do:

```suggestion
  return props.children(useCopyTextHandler(props.text, props))
```
??

2021-02-06 23:39 UTC, mfix22 commented on src/CopyButton.js
> +export function useCopyTextHandler(textToCopy, { interval = 0, ...optionsForCopy } = {}) {
```suggestion
export function useCopyTextHandler(textToCopy, { interval = 0, ...options } = {}) {
```
If you could 🙂

2021-02-06 23:39 UTC, mfix22 commented on README.md
> +    interval = 2 * 1000, // 2 seconds
If you could use 2 spaces here (like this codebase uses) that would be fantastic

2021-02-07 05:36 UTC, Arriv9l commented
Sorry @mfix22 , I am new to ES6 and React. Can I ask one dumb question?
In **README.md**, since I put `interval` and options for [copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard) together as `options`. Why would I still need to keep `props.interval` remain?
```javascript
const options = {
  interval = 2 * 1000, // 2 seconds
  format: "text/html",
}
```
Also, in [TempValue.js](https://github.com/mfix22/actionsack/blob/master/src/TempValue.js), I saw you use `props` to pass parameter here.
```javascript
export const TempValue = React.memo(function TempValue(props) {
  const all = useTempValue(props.initialValue, props)

  return props.children(all)
})
```
But the different between  [TempValue.js](https://github.com/mfix22/actionsack/blob/master/src/TempValue.js) and **CopyButton.js** is:
In [TempValue.js](https://github.com/mfix22/actionsack/blob/master/src/TempValue.js), there are no rest parameters. So you can destructure `props.onSubmit` and `props.onReset` correctly.
```javascript
function useTempValue(initialValue, { onSubmit, onReset } = {})
```
However, since we use rest parameters in **CopyButton.js**, is this still correct to use `props` to pass the parameters?
```javascript
function useCopyTextHandler(textToCopy, { interval = 0, ...optionsForCopy } = {})
```
BTW, that's why I call it `optionsForCopy`. You know, since I put `interval` and `optionsForCopy` together as `options`. 
Excuse my poor English!

2021-02-17 02:11 UTC, mfix22 commented on README.md
> +    interval = 2 * 1000, // 2 seconds
Also, don't think this snippet is value JavaScript. I think you want:
```suggestion
    interval: 2 * 1000, // 2 seconds
```

2021-02-17 02:13 UTC, mfix22 commented
@Arriv9l  Your English is great! Don't worry. 

The reason I asked you to keep interval how it was, is because we still need to support:
```jsx
<CopyButton interval={2000} />
```
not 
```
<CopyButton options={{interval: 2000} />
```

If we don't, that would be a backwards-incompatible change, and would break existing users.

2021-02-17 04:07 UTC, Arriv9l commented
@mfix22  Thanks for your attention.
Now function `useCopyTextHandler` looks like:
```javascript
function useCopyTextHandler(textToCopy, { interval = 0, ...options } = {})
```
So if we do what README.md does:
```javascript
const options = {
  interval: 2 * 1000, // 2 seconds
  format: "text/html",
}
useCopyTextHandler('https://github.com/mfix22/actionsack', options)
```
It will work well. `textToCopy` will get `'https://github.com/mfix22/actionsack'`, `interval` will get `2000`, and the **rest  parameter** `options` will get `{ format: "text/html" }`.
However, if we do:
```javascript
export const CopyButton = React.memo(function CopyButton(props) {
  return props.children(useCopyTextHandler(props.text, props))
})

<CopyButton interval={2000} text={'https://github.com/mfix22/actionsack'} options={{ format: "text/html" }}/>
```
BTW, I might have wrong about the curly braces above, since I’m new to React.
Then `textToCopy` will get `props.text`, which means `'https://github.com/mfix22/actionsack'`; `interval` will get `props.interval`, which means `2000`; but the **rest  parameter** `options` will get something like `{ text:'https://github.com/mfix22/actionsack', format: "text/html" }`. Right?

2021-04-03 23:36 UTC, mfix22 approved these changes

2021-04-03 23:36 UTC, merged

2021-04-03 23:37 UTC, mfix22 commented
Thanks @Arriv9l ! Sorry for the delay